/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package org.hopeconsultants.portlet.tinyurl.model.impl;

import com.liferay.portal.kernel.exception.SystemException;

import org.hopeconsultants.portlet.tinyurl.model.TinyURL;
import org.hopeconsultants.portlet.tinyurl.service.TinyURLLocalServiceUtil;

/**
 * The extended model base implementation for the TinyURL service. Represents a row in the &quot;TinyUrl_TinyURL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TinyURLImpl}.
 * </p>
 *
 * @author Hope Consultants International
 * @see TinyURLImpl
 * @see org.hopeconsultants.portlet.tinyurl.model.TinyURL
 * @generated
 */
public abstract class TinyURLBaseImpl extends TinyURLModelImpl
	implements TinyURL {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tiny u r l model instance should use the {@link TinyURL} interface instead.
	 */
	@Override
	public void persist() throws SystemException {
		if (this.isNew()) {
			TinyURLLocalServiceUtil.addTinyURL(this);
		}
		else {
			TinyURLLocalServiceUtil.updateTinyURL(this);
		}
	}
}