/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.hopeconsultants.tinyurl.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TinyURL service. Represents a row in the &quot;TinyUrl_TinyURL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.hopeconsultants.tinyurl.model.impl.TinyURLModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.hopeconsultants.tinyurl.model.impl.TinyURLImpl}.
 * </p>
 *
 * @author Hope Consultants International
 * @see TinyURL
 * @see org.hopeconsultants.tinyurl.model.impl.TinyURLImpl
 * @see org.hopeconsultants.tinyurl.model.impl.TinyURLModelImpl
 * @generated
 */
@ProviderType
public interface TinyURLModel extends AttachedModel, BaseModel<TinyURL>,
	GroupedModel, ShardedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tiny url model instance should use the {@link TinyURL} interface instead.
	 */

	/**
	 * Returns the primary key of this tiny url.
	 *
	 * @return the primary key of this tiny url
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tiny url.
	 *
	 * @param primaryKey the primary key of this tiny url
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tiny url ID of this tiny url.
	 *
	 * @return the tiny url ID of this tiny url
	 */
	public long getTinyURLId();

	/**
	 * Sets the tiny url ID of this tiny url.
	 *
	 * @param tinyURLId the tiny url ID of this tiny url
	 */
	public void setTinyURLId(long tinyURLId);

	/**
	 * Returns the group ID of this tiny url.
	 *
	 * @return the group ID of this tiny url
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tiny url.
	 *
	 * @param groupId the group ID of this tiny url
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tiny url.
	 *
	 * @return the company ID of this tiny url
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tiny url.
	 *
	 * @param companyId the company ID of this tiny url
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tiny url.
	 *
	 * @return the user ID of this tiny url
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tiny url.
	 *
	 * @param userId the user ID of this tiny url
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tiny url.
	 *
	 * @return the user uuid of this tiny url
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this tiny url.
	 *
	 * @param userUuid the user uuid of this tiny url
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tiny url.
	 *
	 * @return the user name of this tiny url
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tiny url.
	 *
	 * @param userName the user name of this tiny url
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tiny url.
	 *
	 * @return the create date of this tiny url
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tiny url.
	 *
	 * @param createDate the create date of this tiny url
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tiny url.
	 *
	 * @return the modified date of this tiny url
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tiny url.
	 *
	 * @param modifiedDate the modified date of this tiny url
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this tiny url.
	 *
	 * @return the fully qualified class name of this tiny url
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this tiny url.
	 *
	 * @return the class name ID of this tiny url
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this tiny url.
	 *
	 * @param classNameId the class name ID of this tiny url
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this tiny url.
	 *
	 * @return the class pk of this tiny url
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this tiny url.
	 *
	 * @param classPK the class pk of this tiny url
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the code of this tiny url.
	 *
	 * @return the code of this tiny url
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this tiny url.
	 *
	 * @param code the code of this tiny url
	 */
	public void setCode(String code);

	/**
	 * Returns the visible of this tiny url.
	 *
	 * @return the visible of this tiny url
	 */
	public boolean getVisible();

	/**
	 * Returns <code>true</code> if this tiny url is visible.
	 *
	 * @return <code>true</code> if this tiny url is visible; <code>false</code> otherwise
	 */
	public boolean isVisible();

	/**
	 * Sets whether this tiny url is visible.
	 *
	 * @param visible the visible of this tiny url
	 */
	public void setVisible(boolean visible);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TinyURL tinyURL);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TinyURL> toCacheModel();

	@Override
	public TinyURL toEscapedModel();

	@Override
	public TinyURL toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}