/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.hci.portlet.tinyurl.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AttachedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TinyURL service. Represents a row in the &quot;TinyUrl_TinyURL&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.hci.portlet.tinyurl.model.impl.TinyURLModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.hci.portlet.tinyurl.model.impl.TinyURLImpl}.
 * </p>
 *
 * @author Hope Consultants International
 * @see TinyURL
 * @see com.hci.portlet.tinyurl.model.impl.TinyURLImpl
 * @see com.hci.portlet.tinyurl.model.impl.TinyURLModelImpl
 * @generated
 */
public interface TinyURLModel extends AttachedModel, BaseModel<TinyURL>,
	GroupedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tiny u r l model instance should use the {@link TinyURL} interface instead.
	 */

	/**
	 * Returns the primary key of this tiny u r l.
	 *
	 * @return the primary key of this tiny u r l
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tiny u r l.
	 *
	 * @param primaryKey the primary key of this tiny u r l
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the tiny u r l ID of this tiny u r l.
	 *
	 * @return the tiny u r l ID of this tiny u r l
	 */
	public long getTinyURLId();

	/**
	 * Sets the tiny u r l ID of this tiny u r l.
	 *
	 * @param tinyURLId the tiny u r l ID of this tiny u r l
	 */
	public void setTinyURLId(long tinyURLId);

	/**
	 * Returns the group ID of this tiny u r l.
	 *
	 * @return the group ID of this tiny u r l
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this tiny u r l.
	 *
	 * @param groupId the group ID of this tiny u r l
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this tiny u r l.
	 *
	 * @return the company ID of this tiny u r l
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this tiny u r l.
	 *
	 * @param companyId the company ID of this tiny u r l
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this tiny u r l.
	 *
	 * @return the user ID of this tiny u r l
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this tiny u r l.
	 *
	 * @param userId the user ID of this tiny u r l
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this tiny u r l.
	 *
	 * @return the user uuid of this tiny u r l
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this tiny u r l.
	 *
	 * @param userUuid the user uuid of this tiny u r l
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this tiny u r l.
	 *
	 * @return the user name of this tiny u r l
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this tiny u r l.
	 *
	 * @param userName the user name of this tiny u r l
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this tiny u r l.
	 *
	 * @return the create date of this tiny u r l
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this tiny u r l.
	 *
	 * @param createDate the create date of this tiny u r l
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this tiny u r l.
	 *
	 * @return the modified date of this tiny u r l
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this tiny u r l.
	 *
	 * @param modifiedDate the modified date of this tiny u r l
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the fully qualified class name of this tiny u r l.
	 *
	 * @return the fully qualified class name of this tiny u r l
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this tiny u r l.
	 *
	 * @return the class name ID of this tiny u r l
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this tiny u r l.
	 *
	 * @param classNameId the class name ID of this tiny u r l
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class p k of this tiny u r l.
	 *
	 * @return the class p k of this tiny u r l
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class p k of this tiny u r l.
	 *
	 * @param classPK the class p k of this tiny u r l
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the code of this tiny u r l.
	 *
	 * @return the code of this tiny u r l
	 */
	@AutoEscape
	public String getCode();

	/**
	 * Sets the code of this tiny u r l.
	 *
	 * @param code the code of this tiny u r l
	 */
	public void setCode(String code);

	/**
	 * Returns the visible of this tiny u r l.
	 *
	 * @return the visible of this tiny u r l
	 */
	public boolean getVisible();

	/**
	 * Returns <code>true</code> if this tiny u r l is visible.
	 *
	 * @return <code>true</code> if this tiny u r l is visible; <code>false</code> otherwise
	 */
	public boolean isVisible();

	/**
	 * Sets whether this tiny u r l is visible.
	 *
	 * @param visible the visible of this tiny u r l
	 */
	public void setVisible(boolean visible);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.hci.portlet.tinyurl.model.TinyURL tinyURL);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.hci.portlet.tinyurl.model.TinyURL> toCacheModel();

	@Override
	public com.hci.portlet.tinyurl.model.TinyURL toEscapedModel();

	@Override
	public com.hci.portlet.tinyurl.model.TinyURL toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}